version: 1
# The name of your project. This should match the project name on Read the Docs.
name: custom_api_client

# The version of your project (usually 'main' or the default branch).
version: main

# The build configuration. You can specify the operating system and tools.
build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

# The source directory where your documentation is located.
source:
  dir: docs

# The requirements to install during the build process.
requirements:
  files:
    - requirements.txt
