version: 2
name: custom_api_client
version: main

# The build configuration
build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

source:
  dir: docs  # Path where your documentation files (e.g., index.rst) are located

# Requirements
requirements:
  files:
    - requirements.txt
